/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAiRoutingRouteImport } from './routes/admin.ai-routing'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiAdminAiRoutingRouteImport } from './routes/api/admin/ai-routing'
import { Route as ApiAiConversationChatRouteImport } from './routes/api/ai/conversation/chat'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoutingRoute = AdminAiRoutingRouteImport.update({
  id: '/admin/ai-routing',
  path: '/admin/ai-routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiRoutingRoute = ApiAdminAiRoutingRouteImport.update({
  id: '/api/admin/ai-routing',
  path: '/api/admin/ai-routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConversationChatRoute = ApiAiConversationChatRouteImport.update({
  id: '/api/ai/conversation/chat',
  path: '/api/ai/conversation/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/ai-routing': typeof AdminAiRoutingRoute
  '/api/products': typeof ApiProductsRoute
  '/api/admin/ai-routing': typeof ApiAdminAiRoutingRoute
  '/api/ai/conversation/chat': typeof ApiAiConversationChatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/ai-routing': typeof AdminAiRoutingRoute
  '/api/products': typeof ApiProductsRoute
  '/api/admin/ai-routing': typeof ApiAdminAiRoutingRoute
  '/api/ai/conversation/chat': typeof ApiAiConversationChatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/ai-routing': typeof AdminAiRoutingRoute
  '/api/products': typeof ApiProductsRoute
  '/api/admin/ai-routing': typeof ApiAdminAiRoutingRoute
  '/api/ai/conversation/chat': typeof ApiAiConversationChatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/ai-routing'
    | '/api/products'
    | '/api/admin/ai-routing'
    | '/api/ai/conversation/chat'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/ai-routing'
    | '/api/products'
    | '/api/admin/ai-routing'
    | '/api/ai/conversation/chat'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin/ai-routing'
    | '/api/products'
    | '/api/admin/ai-routing'
    | '/api/ai/conversation/chat'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAiRoutingRoute: typeof AdminAiRoutingRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiAdminAiRoutingRoute: typeof ApiAdminAiRoutingRoute
  ApiAiConversationChatRoute: typeof ApiAiConversationChatRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-routing': {
      id: '/admin/ai-routing'
      path: '/admin/ai-routing'
      fullPath: '/admin/ai-routing'
      preLoaderRoute: typeof AdminAiRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai-routing': {
      id: '/api/admin/ai-routing'
      path: '/api/admin/ai-routing'
      fullPath: '/api/admin/ai-routing'
      preLoaderRoute: typeof ApiAdminAiRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/conversation/chat': {
      id: '/api/ai/conversation/chat'
      path: '/api/ai/conversation/chat'
      fullPath: '/api/ai/conversation/chat'
      preLoaderRoute: typeof ApiAiConversationChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAiRoutingRoute: AdminAiRoutingRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiAdminAiRoutingRoute: ApiAdminAiRoutingRoute,
  ApiAiConversationChatRoute: ApiAiConversationChatRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
